### ISSUE TITLE
id values exceed: 100000000

### ISSUE THREAD

**Issue by Cugar15** [tokiwinter/cloudns-api#11]
An integer check for the id is coded with a maz value of 100000000 (line: 1115).

Looks like the ids in clouDNS exceed this value.

Fx is to add another 0 - until this ID range is exeeded.

**Comment by tokiwinter** [comment]
Thanks - fixed in 80d11ebc7711a043907b64e6462561361c23f016 - I should really write a smarter way of handling this, but for now, this should fix the issue.
