### ISSUE TITLE
Need another maintainer

### ISSUE THREAD

**Issue by tokiwinter** [tokiwinter/cloudns-api#6]
If anybody wants to help maintain this, please let me know.

Unfortunately, I am very busy (as evidenced by it taking me six months to review two PRs).

Thanks!

**Comment by trunet** [comment]
I can take care of it.

**Comment by tokiwinter** [comment]
@trunet - an invite is on the way - welcome and thanks :)

**Comment by trunet** [comment]
thanks, can I license the code under GPLv3?

**Comment by tokiwinter** [comment]
For sure 👍
