### ISSUE TITLE
CentOS 7: old bash version doesn't support local -n

### ISSUE THREAD

**Issue by ghost** [tokiwinter/cloudns-api#8]
Hello ! First of all thanks for te script, I successfully created a master zone this way
          cloudns_api.sh addzone 'api.net&master'

Then I attempt to create A record this way
         cloudns_api.sh addrecord api.net type=A host=www record=201.139.116.6 ttl=3600

And i got this
        /usr/bin/cloudns_api: línea 275: local: -n: opción inválida
local: uso: local [opción] nombre[=valor] ...
mar dic 12 16:12:52 CST 2017: Error: type is not a valid key
/usr/bin/cloudns_api: línea 275: local: -n: opción inválida
local: uso: local [opción] nombre[=valor] ...
mar dic 12 16:12:52 CST 2017: Error: host is not a valid key
/usr/bin/cloudns_api: línea 275: local: -n: opción inválida
local: uso: local [opción] nombre[=valor] ...
mar dic 12 16:12:52 CST 2017: Error: record is not a valid key
/usr/bin/cloudns_api: línea 275: local: -n: opción inválida
local: uso: local [opción] nombre[=valor] ...
mar dic 12 16:12:52 CST 2017: Error: ttl is not a valid key

Could you help me to know what is wrong ? I am running the script in Centos 7. Thanks in advanced !

**Comment by tokiwinter** [comment]
The version of `bash` supplied with CentOS 7 is too old. You can do something like:
```
cd /usr/local/src
wget http://ftp.gnu.org/gnu/bash/bash-4.4.12.tar.gz
wget http://ftp.gnu.org/gnu/bash/bash-4.4.12.tar.gz.sig
gpg2 --recv-keys 64EA74AB
gpg2 --verify bash-4.4.12.tar.gz.sig bash-4.4.12.tar.gz
tar xzf bash-4.4.12.tar.gz
cd bash-4.4.12
./configure --prefix=/usr/local/$( basename $( pwd ) )
make
make install
ln -sf /usr/local/$( basename $( pwd ) )/bin/bash /bin/bash4.4
```
Then edit the shebang in `cloudns-api.sh` to `#!/bin/bash4.4` and it should work fine.

**Comment by ghost** [comment]
Thanks a lot !, everything works fine with bash 4.4 
Have a nice day !
