### ISSUE TITLE
id record value

### ISSUE THREAD

**Issue by solead** [tokiwinter/cloudns-api#9]
Hello.

Why it's showing this error when I try to get the id records?

# ./cloudns_api.sh listrecords domain.xxx showid=true
./cloudns_api.sh: line 275: local: -n: invalid option
local: usage: local [option] name[=value] ...
Error: showid is not a valid key

Tks

**Comment by tokiwinter** [comment]
Hello,

Please see https://github.com/tokiwinter/cloudns-api/issues/8

Thanks!
